### ISSUE TITLE
Question:Behave Graph Execution Environment

### ISSUE THREAD

**Issue by Hackn0214** [KhronosGroup/glTF-InteractivityGraph-AuthoringTool#23]
I am using the Chrome browser on Windows 10, but I cannot verify the behavior of KHR_interactivity.
I loaded and ran the NeedleAnimatedCharacter.glb in the Babylon Engine, but only a T-pose model is displayed.
Is there any pre-configuration required when launching this DCC app?

**Comment by Hackn0214** [comment]
It seems like the image is corrupted, so I will re-upload it.
![NeedleAnimatedCharacter](https://github.com/user-attachments/assets/cfe82dac-e51d-4ed8-a6a9-ebb7fe68dbd4)

**Comment by Hackn0214** [comment]
It worked!
It seems that it might be affected by the (glb)file loaded beforehand.
I suspect the initialization is not going smoothly.

**Comment by mattmacf98** [comment]
I am unable to help unless I have some reproduction steps (a video of the issue would be even better!)

**Comment by Hackn0214** [comment]
Thank you, Matthew 
As I mentioned in Issue #22, the Behave Graph Authoring graph is not updated when loading a glb file, which seems to be causing unexpected behavior.
It would be helpful if the Graph window could be cleared automatically when loading a glb file, or if there was a manual way to clear the Graph window.
Currently, I am deleting nodes one by one.

**Comment by Hackn0214** [comment]
Upon further consideration, it's common for gltf files to not include KHR_interactivity, so keeping the graph by default is fine.
Currently, I’m experimenting with exporting glb files with KHR_interactivity using the 3ds Max, so it would be helpful if the Behave Graph could be cleared before loading the file, but only when the file includes KHR_interactivity.

**Comment by mattmacf98** [comment]
https://github.com/user-attachments/assets/a04c3590-2192-4da4-ad0f-7300bc8dfd67

I have made it so that when a new glTF WITH interactivity is loaded, it will update the graph the video covers testing the following cases

1. a graph is present and a non interactive glb is loaded -> keep graph
2. a graph present and an interactive glb loaded -> replace graph
3. an interactive glb loaded, the graph is change , play is pressed -> keep current editted state of graph (do not replace with the one inside the glb)
